import React, { useState } from 'react';
import './styles/AadhaarUpdate.css'; // Ensure this CSS file exists

const AadhaarUpdate = () => {
  const [activeFAQ, setActiveFAQ] = useState(null);

  // Toggle FAQ visibility
  const toggleFAQ = (index) => {
    setActiveFAQ(activeFAQ === index ? null : index);
  };

  // FAQ Data
  const faqs = [
    {
      question: 'What is the expiry period of VID?',
      answer:
        'A VID (Virtual ID) is valid until a new VID is generated by the Aadhaar holder. There is no fixed expiry for it.',
    },
    {
      question: 'How can I update my mobile number in Aadhaar?',
      answer:
        'You need to visit the nearest Aadhaar Enrollment Center to update your mobile number in Aadhaar.',
    },
    {
      question: 'Can I update my address online without documents?',
      answer:
        'Yes, using the Address Validation Letter service if you do not have valid address proof.',
    },
  ];

  return (
    <div className="aadhaar-container">
      <h1 className="aadhaar-title">Update Your Aadhaar</h1>

      {/* Update Services Section */}
      <section className="update-section">
        <div className="update-service">
          <h2>Aadhaar Update Services</h2>

          {/* Document Update */}
          <div className="update-box">
            <h3>Document Update</h3>
            <p>Update your Aadhaar documents for accurate authentication.</p>
            <a
              href="https://myaadhaar.uidai.gov.in/du/en_IN"
              target="_blank"
              rel="noopener noreferrer"
            >
              Document Update
            </a>
          </div>

          {/* Supporting Documents */}
          <div className="update-box">
            <h3>List Of Supporting Documents (PDF)</h3>
            <p>View the list of acceptable supporting documents for Aadhaar updates.</p>
            <a
              href="https://uidai.gov.in/images/commdoc/List_of_Supporting_Document_for_Aadhaar_Enrolment_and_Update.pdf"
              target="_blank"
              rel="noopener noreferrer"
            >
              Download PDF
            </a>
          </div>

          {/* Address Update */}
          <div className="update-box">
            <h3>Update Address in your Aadhaar</h3>
            <p>
              Moved to a new address? Update your Aadhaar details with valid proof or an
              Address Validation Letter.
            </p>
            <a
              href="https://myaadhaar.uidai.gov.in/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Update Address
            </a>
          </div>

          {/* Enrollment Forms */}
          <div className="update-box">
            <h3>Enrolment & Update Forms</h3>
            <p>Access Aadhaar enrolment and update forms.</p>
            <a
              href="https://uidai.gov.in/en/my-aadhaar/downloads/enrolment-and-update-forms.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Download Forms
            </a>
          </div>
        </div>
      </section>

      {/* Reference Section */}
      <div className="reference-section">
        <h3>References</h3>
        <ul>
          <li>
            <a
              href="https://uidai.gov.in/en/my-aadhaar/downloads/enrolment-and-update-forms.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Aadhaar Update/Correction Form
            </a>
          </li>
          <li>
            <a
              href="https://uidai.gov.in/images/commdoc/List_of_Supporting_Document_for_Aadhaar_Enrolment_and_Update.pdf"
              target="_blank"
              rel="noopener noreferrer"
            >
              List of Supporting Documents PDF
            </a>
          </li>
          <li>
            <a
              href="https://uidai.gov.in/images/akr_policy_on_pricing_30082016.pdf"
              target="_blank"
              rel="noopener noreferrer"
            >
              Charges for Various UIDAI Services
            </a>
          </li>
          <li>
            <a
              href="https://uidai.gov.in/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Validity of downloaded Aadhaar (e-Aadhaar)
            </a>
          </li>
        </ul>
      </div>

      {/* FAQ Section */}
      <section className="service-section">
        <div className="faq-box">
          <h3>Frequently Asked Questions</h3>
          <div className="faq-list">
            {faqs.map((faq, index) => (
              <div className="faq-item" key={index}>
                <button
                  className="faq-question"
                  onClick={() => toggleFAQ(index)}
                >
                  {faq.question}
                </button>
                {activeFAQ === index && (
                  <div className="faq-answer">{faq.answer}</div>
                )}
              </div>
            ))}
            <a
              href="https://uidai.gov.in/faqs.html"
              className="faq-view-all"
              target="_blank"
              rel="noopener noreferrer"
            >
              View All FAQs
            </a>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AadhaarUpdate;
